# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seqence.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='seqence.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rseqence.proto\"\x17\n\tSeqenceID\x12\n\n\x02id\x18\x01 \x01(\x03\"\x1e\n\x07Request\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t2)\n\x07Seqence\x12\x1e\n\x06get_id\x12\x08.Request\x1a\n.SeqenceIDb\x06proto3'
)




_SEQENCEID = _descriptor.Descriptor(
  name='SeqenceID',
  full_name='SeqenceID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SeqenceID.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=40,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_name', full_name='Request.client_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['SeqenceID'] = _SEQENCEID
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SeqenceID = _reflection.GeneratedProtocolMessageType('SeqenceID', (_message.Message,), {
  'DESCRIPTOR' : _SEQENCEID,
  '__module__' : 'seqence_pb2'
  # @@protoc_insertion_point(class_scope:SeqenceID)
  })
_sym_db.RegisterMessage(SeqenceID)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'seqence_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)



_SEQENCE = _descriptor.ServiceDescriptor(
  name='Seqence',
  full_name='Seqence',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=74,
  serialized_end=115,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_id',
    full_name='Seqence.get_id',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_SEQENCEID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEQENCE)

DESCRIPTOR.services_by_name['Seqence'] = _SEQENCE

# @@protoc_insertion_point(module_scope)
